# Auto-generated usage data.

API_USAGE_DATA = {'title': 'LogiKlu Focus API Guide',
 'subtitle': 'Client-facing developer guide for LogiKlu Focus Account Intelligence APIs using OAuth 2.0 Bearer JWT '
             'authentication.',
 'base_url': 'https://api.logiklu.com',
 'sandbox_base_url': 'https://sandboxapi.logiklu.com',
 'local_base_url': 'http://127.0.0.1:8000',
 'api_version': 'v1',
 'auth_badge': 'Bearer JWT',
 'quick_start_auth_type': 'bearer',
 'auth': {'title': 'Authentication',
          'description': 'Protected APIs use OAuth 2.0 Client Credentials with a short-lived Bearer JWT. First '
                         'generate an access token from /oauth/token, then send it in the Authorization header.',
          'headers': [{'name': 'Authorization',
                       'required': 'Yes',
                       'description': 'Use Bearer authentication for protected APIs. Format: Authorization: Bearer '
                                      '<access_token>.'}],
          'token_endpoint': {'method': 'POST',
                             'path': '/oauth/token',
                             'auth': 'No Auth',
                             'content_type': 'application/json',
                             'description': 'Generate a short-lived access token using the OAuth client credentials '
                                            'flow.',
                             'request_body': {'client_id': 'OAuth client ID provided by LogiKlu.',
                                              'client_secret': 'Client secret provided by LogiKlu. Keep this private.',
                                              'grant_type': 'client_credentials'},
                             'response_fields': {'access_token': 'JWT access token to be sent as Bearer token.',
                                                 'token_type': 'Bearer',
                                                 'expires_in': 'Token lifetime in seconds. Current default is 900 '
                                                               'seconds.',
                                                 'scope': 'Allowed API permissions/scopes.'}}},
 'response_format': {'success': {'status': 'success',
                                 'message': 'Focus Account Intelligence fetched successfully',
                                 'meta': {'generated_at': '2026-07-03T10:00:00+00:00',
                                          'page': 1,
                                          'per_page': 10,
                                          'record_count': 10},
                                 'data': {'logiklu_account_inetellegence': []}},
                     'error': {'status': 'error',
                               'message': 'Missing API key or bearer token',
                               'error_code': 'AUTH_CREDENTIALS_MISSING',
                               'meta': {'timestamp': '2026-07-03T10:00:00+00:00'},
                               'data': None}},
 'notes': [{'title': 'OAuth token flow',
            'description': 'Call /oauth/token with client_id, client_secret, and grant_type=client_credentials. Then '
                           'send the returned access_token as Authorization: Bearer <access_token>.'},
           {'title': 'Bearer token expiry',
            'description': 'Access tokens are short-lived. The current default expiry is 900 seconds. Generate a new '
                           'token when the previous token expires.'},
           {'title': 'No JWT secret sharing',
            'description': 'JWT_SECRET_KEY is an internal LogiKlu server secret. It must never be shared with API '
                           'consumers.'},
           {'title': 'Clean endpoint paths',
            'description': 'Public API routes use clean paths such as /oauth/token and /focus/account-intelligence. Do '
                           'not prefix these routes with /api/v1.'},
           {'title': 'API logging',
            'description': 'API requests are logged internally for audit, troubleshooting, and support. Sandbox and '
                           'production logs are stored separately.'},
           {'title': 'Focus dynamic search',
            'description': '/focus/account-intelligence supports general search, search_by, account/company filters, '
                           'linked contact filters, priority/interest filters, and score range filters.'},
           {'title': 'Score range filters',
            'description': 'Use *_score_min and *_score_max query parameters such as activity_score_min, '
                           'depth_score_max, final_score_min, and total_score_max.'},
           {'title': 'Contact filters without duplicate accounts',
            'description': 'contact_name, contact_email, and contact_phone filter accounts by linked contacts without '
                           'duplicating company/account rows.'}],
 'sections': [{'id': 'authentication',
               'title': 'OAuth / JWT Authentication',
               'description': 'Generate a Bearer access token using client credentials, then call protected APIs with '
                              'Authorization: Bearer <access_token>.',
               'endpoints': [{'id': 'oauth-token',
                              'title': 'Generate Access Token',
                              'method': 'POST',
                              'path': '/oauth/token',
                              'purpose': 'Generate a Bearer access token using the client credentials provided by '
                                         'LogiKlu.',
                              'auth_type': 'none',
                              'request_type': 'JSON Body',
                              'parameters': [{'name': 'client_id',
                                              'type': 'string',
                                              'required': 'Yes',
                                              'example': 'lkc_3f2a6a9eae2c4b2db37f9875f0e9a111',
                                              'description': 'OAuth client ID provided by LogiKlu.'},
                                             {'name': 'client_secret',
                                              'type': 'string',
                                              'required': 'Yes',
                                              'example': 'provided_client_secret',
                                              'description': 'Client secret provided by LogiKlu. Keep this private and '
                                                             'never expose it in frontend code.'},
                                             {'name': 'grant_type',
                                              'type': 'string',
                                              'required': 'Yes',
                                              'example': 'client_credentials',
                                              'description': 'Must be client_credentials.'}],
                              'body': {'client_id': 'YOUR_CLIENT_ID',
                                       'client_secret': 'YOUR_CLIENT_SECRET',
                                       'grant_type': 'client_credentials'},
                              'examples': [{'title': 'Generate token',
                                            'description': 'Call this endpoint with No Auth. Use the returned '
                                                           'access_token as Bearer token for protected APIs.',
                                            'path': '/oauth/token',
                                            'body': {'client_id': 'YOUR_CLIENT_ID',
                                                     'client_secret': 'YOUR_CLIENT_SECRET',
                                                     'grant_type': 'client_credentials'}}],
                              'response_example': {'access_token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
                                                   'token_type': 'Bearer',
                                                   'expires_in': 900,
                                                   'scope': 'focus:account-intelligence:read'}}]},
              {'id': 'focus-account-intelligence',
               'title': 'Focus Account Intelligence',
               'description': 'Use Focus Account Intelligence APIs to read LogiKlu Focus buying-intent signals, score '
                              'components, priority score, interest level, evidence facts, linked contacts, and '
                              'journey intelligence. The list API supports account-style dynamic search plus '
                              'Focus-specific score and contact filters.',
               'endpoints': [{'id': 'focus-account-intelligence-list',
                              'title': 'Focus Account Intelligence List',
                              'method': 'GET',
                              'path': '/focus/account-intelligence',
                              'purpose': 'Fetch Focus Account Intelligence records with dynamic search, '
                                         'account/company filters, linked contact filters, score range filters, '
                                         'priority filters, pagination, signal summary, and journey intelligence. '
                                         'Journey data is included by default.',
                              'auth_type': 'bearer',
                              'request_type': 'Query Parameters',
                              'parameters': [{'name': 'page',
                                              'type': 'integer',
                                              'required': 'No',
                                              'example': '1',
                                              'description': 'Page number. Default is 1.'},
                                             {'name': 'per_page',
                                              'type': 'integer',
                                              'required': 'No',
                                              'example': '10',
                                              'description': 'Number of records per page. Maximum value is 100.'},
                                             {'name': 'search',
                                              'type': 'string',
                                              'required': 'No',
                                              'example': 'LogiKlu',
                                              'description': 'General search across company/account fields, location, '
                                                             'website, industry, contact name/email/phone, interest '
                                                             'level, priority label, and engagement level.'},
                                             {'name': 'search_by',
                                              'type': 'string',
                                              'required': 'No',
                                              'example': 'contact_email',
                                              'description': 'Search only one selected field. Example values: '
                                                             'company_name, website, country, contact_email, '
                                                             'priority_label, final_score.'},
                                             {'name': 'filters',
                                              'type': 'JSON string',
                                              'required': 'No',
                                              'example': '[{"field":"final_score","operator":"between","value":[50,100]}]',
                                              'description': 'Advanced JSON filters for field/operator/value '
                                                             'filtering. Useful for between, gte, lte, in, eq, and '
                                                             'like style filtering.'},
                                             {'name': 'account_id',
                                              'type': 'integer/string',
                                              'required': 'No',
                                              'example': '1094',
                                              'description': 'Filter by exact account ID / lead ID.'},
                                             {'name': 'lead_id',
                                              'type': 'integer/string',
                                              'required': 'No',
                                              'example': '1094',
                                              'description': 'Alias for account_id. Filter by exact lead/account ID.'},
                                             {'name': 'company_name',
                                              'type': 'string',
                                              'required': 'No',
                                              'example': 'LogiKlu',
                                              'description': 'Filter by company/account name.'},
                                             {'name': 'account_name',
                                              'type': 'string',
                                              'required': 'No',
                                              'example': 'LogiKlu',
                                              'description': 'Alias for company_name. Filter by account name.'},
                                             {'name': 'lead_name',
                                              'type': 'string',
                                              'required': 'No',
                                              'example': 'LogiKlu',
                                              'description': 'Filter by CRM lead/account name.'},
                                             {'name': 'website',
                                              'type': 'string',
                                              'required': 'No',
                                              'example': 'logiklu.com',
                                              'description': 'Filter by company website/domain.'},
                                             {'name': 'company_domain',
                                              'type': 'string',
                                              'required': 'No',
                                              'example': 'logiklu.com',
                                              'description': 'Alias for website. Filter by company domain.'},
                                             {'name': 'industry',
                                              'type': 'string',
                                              'required': 'No',
                                              'example': 'Software',
                                              'description': 'Filter by industry. Comma-separated values are '
                                                             'supported.'},
                                             {'name': 'city',
                                              'type': 'string',
                                              'required': 'No',
                                              'example': 'Kolkata',
                                              'description': 'Filter by city.'},
                                             {'name': 'state',
                                              'type': 'string',
                                              'required': 'No',
                                              'example': 'West Bengal',
                                              'description': 'Filter by state.'},
                                             {'name': 'country',
                                              'type': 'string',
                                              'required': 'No',
                                              'example': 'India,Japan',
                                              'description': 'Filter by one or more countries. Comma-separated values '
                                                             'are supported.'},
                                             {'name': 'email',
                                              'type': 'string',
                                              'required': 'No',
                                              'example': 'sales@',
                                              'description': 'Filter by account/company email.'},
                                             {'name': 'phone',
                                              'type': 'string',
                                              'required': 'No',
                                              'example': '9876',
                                              'description': 'Filter by account/company phone.'},
                                             {'name': 'owner',
                                              'type': 'integer/string',
                                              'required': 'No',
                                              'example': '4',
                                              'description': 'Filter by account owner user ID where available.'},
                                             {'name': 'lead_category',
                                              'type': 'string',
                                              'required': 'No',
                                              'example': 'lead',
                                              'description': 'Filter by lead category.'},
                                             {'name': 'lead_type',
                                              'type': 'string',
                                              'required': 'No',
                                              'example': 'hot',
                                              'description': 'Filter by lead type/temperature.'},
                                             {'name': 'lead_status',
                                              'type': 'string',
                                              'required': 'No',
                                              'example': 'active',
                                              'description': 'Filter by lead status.'},
                                             {'name': 'active_status',
                                              'type': 'string',
                                              'required': 'No',
                                              'example': 'active',
                                              'description': 'Filter by active/archive status.'},
                                             {'name': 'contact_name',
                                              'type': 'string',
                                              'required': 'No',
                                              'example': 'John',
                                              'description': 'Filter accounts whose linked contacts match this name. '
                                                             'Uses contact lookup without duplicating company rows.'},
                                             {'name': 'contact_email',
                                              'type': 'string',
                                              'required': 'No',
                                              'example': 'gmail.com',
                                              'description': 'Filter accounts whose linked contacts match this '
                                                             'email/domain.'},
                                             {'name': 'contact_phone',
                                              'type': 'string',
                                              'required': 'No',
                                              'example': '9876',
                                              'description': 'Filter accounts whose linked contacts match this phone '
                                                             'number.'},
                                             {'name': 'interest_level',
                                              'type': 'string',
                                              'required': 'No',
                                              'example': 'High',
                                              'description': 'Filter by interest level / interest category. '
                                                             'Comma-separated values are supported.'},
                                             {'name': 'priority_label',
                                              'type': 'string',
                                              'required': 'No',
                                              'example': 'Hot,Warm',
                                              'description': 'Filter by priority label such as Hot, Warm, Monitor, '
                                                             'Low. Comma-separated values are supported.'},
                                             {'name': 'priority_level',
                                              'type': 'string',
                                              'required': 'No',
                                              'example': 'Hot',
                                              'description': 'Alias for priority_label.'},
                                             {'name': 'engagement_level',
                                              'type': 'string',
                                              'required': 'No',
                                              'example': 'High',
                                              'description': 'Filter by engagement level where available.'},
                                             {'name': 'is_shortlisted',
                                              'type': 'boolean/string',
                                              'required': 'No',
                                              'example': 'true',
                                              'description': 'Filter shortlisted records. Supported values include '
                                                             'true/false, 1/0, Y/N where implemented.'},
                                             {'name': 'activity_score_min',
                                              'type': 'number',
                                              'required': 'No',
                                              'example': '20',
                                              'description': 'Minimum activity score.'},
                                             {'name': 'activity_score_max',
                                              'type': 'number',
                                              'required': 'No',
                                              'example': '80',
                                              'description': 'Maximum activity score.'},
                                             {'name': 'depth_score_min',
                                              'type': 'number',
                                              'required': 'No',
                                              'example': '10',
                                              'description': 'Minimum depth score.'},
                                             {'name': 'depth_score_max',
                                              'type': 'number',
                                              'required': 'No',
                                              'example': '60',
                                              'description': 'Maximum depth score.'},
                                             {'name': 'sustenance_score_min',
                                              'type': 'number',
                                              'required': 'No',
                                              'example': '10',
                                              'description': 'Minimum sustenance score.'},
                                             {'name': 'sustenance_score_max',
                                              'type': 'number',
                                              'required': 'No',
                                              'example': '50',
                                              'description': 'Maximum sustenance score.'},
                                             {'name': 'sustainment_score_min',
                                              'type': 'number',
                                              'required': 'No',
                                              'example': '10',
                                              'description': 'Alias for sustenance_score_min.'},
                                             {'name': 'sustainment_score_max',
                                              'type': 'number',
                                              'required': 'No',
                                              'example': '50',
                                              'description': 'Alias for sustenance_score_max.'},
                                             {'name': 'context_score_min',
                                              'type': 'number',
                                              'required': 'No',
                                              'example': '5',
                                              'description': 'Minimum context score.'},
                                             {'name': 'context_score_max',
                                              'type': 'number',
                                              'required': 'No',
                                              'example': '30',
                                              'description': 'Maximum context score.'},
                                             {'name': 'contextual_score_min',
                                              'type': 'number',
                                              'required': 'No',
                                              'example': '5',
                                              'description': 'Alias for context_score_min.'},
                                             {'name': 'contextual_score_max',
                                              'type': 'number',
                                              'required': 'No',
                                              'example': '30',
                                              'description': 'Alias for context_score_max.'},
                                             {'name': 'conversion_score_min',
                                              'type': 'number',
                                              'required': 'No',
                                              'example': '0',
                                              'description': 'Minimum conversion score.'},
                                             {'name': 'conversion_score_max',
                                              'type': 'number',
                                              'required': 'No',
                                              'example': '100',
                                              'description': 'Maximum conversion score.'},
                                             {'name': 'interest_score_min',
                                              'type': 'number',
                                              'required': 'No',
                                              'example': '25',
                                              'description': 'Minimum interest score.'},
                                             {'name': 'interest_score_max',
                                              'type': 'number',
                                              'required': 'No',
                                              'example': '100',
                                              'description': 'Maximum interest score.'},
                                             {'name': 'priority_score_min',
                                              'type': 'number',
                                              'required': 'No',
                                              'example': '50',
                                              'description': 'Minimum priority score.'},
                                             {'name': 'priority_score_max',
                                              'type': 'number',
                                              'required': 'No',
                                              'example': '100',
                                              'description': 'Maximum priority score.'},
                                             {'name': 'final_score_min',
                                              'type': 'number',
                                              'required': 'No',
                                              'example': '50',
                                              'description': 'Minimum final score.'},
                                             {'name': 'final_score_max',
                                              'type': 'number',
                                              'required': 'No',
                                              'example': '100',
                                              'description': 'Maximum final score.'},
                                             {'name': 'total_score_min',
                                              'type': 'number',
                                              'required': 'No',
                                              'example': '50',
                                              'description': 'Alias for final_score_min / total score minimum.'},
                                             {'name': 'total_score_max',
                                              'type': 'number',
                                              'required': 'No',
                                              'example': '100',
                                              'description': 'Alias for final_score_max / total score maximum.'}],
                              'examples': [{'title': 'Get first page of Focus Account Intelligence',
                                            'description': 'Retrieve the first page of account intelligence records.',
                                            'path': '/focus/account-intelligence',
                                            'query': {'page': 1, 'per_page': 10}},
                                           {'title': 'General search across accounts and contacts',
                                            'description': 'Search company, location, website, industry, priority, '
                                                           'interest level, and linked contact fields using one search '
                                                           'value.',
                                            'path': '/focus/account-intelligence',
                                            'query': {'search': 'LogiKlu', 'page': 1, 'per_page': 10}},
                                           {'title': 'Search by a specific field',
                                            'description': 'Search only linked contact email using search_by.',
                                            'path': '/focus/account-intelligence',
                                            'query': {'search': 'gmail.com',
                                                      'search_by': 'contact_email',
                                                      'page': 1,
                                                      'per_page': 10}},
                                           {'title': 'Filter by company and country',
                                            'description': 'Filter by company name and one or more countries.',
                                            'path': '/focus/account-intelligence',
                                            'query': {'company_name': 'LogiKlu',
                                                      'country': 'India,Japan',
                                                      'page': 1,
                                                      'per_page': 10}},
                                           {'title': 'Filter by website/domain',
                                            'description': 'Find intelligence records for accounts matching a '
                                                           'website/domain.',
                                            'path': '/focus/account-intelligence',
                                            'query': {'website': 'logiklu.com', 'page': 1, 'per_page': 10}},
                                           {'title': 'Filter by linked contact email',
                                            'description': 'Return accounts where any linked contact email matches the '
                                                           'provided value.',
                                            'path': '/focus/account-intelligence',
                                            'query': {'contact_email': 'gmail.com', 'page': 1, 'per_page': 10}},
                                           {'title': 'Filter by linked contact name and phone',
                                            'description': 'Return accounts where linked contacts match name or phone '
                                                           'filters.',
                                            'path': '/focus/account-intelligence',
                                            'query': {'contact_name': 'John',
                                                      'contact_phone': '9876',
                                                      'page': 1,
                                                      'per_page': 10}},
                                           {'title': 'Filter by priority and interest level',
                                            'description': 'Fetch high-intent records by combining priority and '
                                                           'interest filters.',
                                            'path': '/focus/account-intelligence',
                                            'query': {'priority_label': 'Hot,Warm',
                                                      'interest_level': 'High',
                                                      'page': 1,
                                                      'per_page': 10}},
                                           {'title': 'Filter shortlisted records',
                                            'description': 'Fetch only shortlisted Focus accounts.',
                                            'path': '/focus/account-intelligence',
                                            'query': {'is_shortlisted': 'true', 'page': 1, 'per_page': 10}},
                                           {'title': 'Filter by activity and depth score ranges',
                                            'description': 'Return accounts whose activity and depth scores fall '
                                                           'within the requested ranges.',
                                            'path': '/focus/account-intelligence',
                                            'query': {'activity_score_min': 20,
                                                      'activity_score_max': 80,
                                                      'depth_score_min': 10,
                                                      'depth_score_max': 60,
                                                      'page': 1,
                                                      'per_page': 10}},
                                           {'title': 'Filter by final score range',
                                            'description': 'Return accounts whose final score is between 50 and 100.',
                                            'path': '/focus/account-intelligence',
                                            'query': {'final_score_min': 50,
                                                      'final_score_max': 100,
                                                      'page': 1,
                                                      'per_page': 10}},
                                           {'title': 'Filter by total score alias',
                                            'description': 'Use total_score_min and total_score_max as aliases for '
                                                           'final score range filtering.',
                                            'path': '/focus/account-intelligence',
                                            'query': {'total_score_min': 50,
                                                      'total_score_max': 100,
                                                      'page': 1,
                                                      'per_page': 10}},
                                           {'title': 'Combined account, contact, and score filtering',
                                            'description': 'Example of combining company, contact email, priority, and '
                                                           'score range filters.',
                                            'path': '/focus/account-intelligence',
                                            'query': {'industry': 'Software',
                                                      'contact_email': 'gmail.com',
                                                      'priority_label': 'Hot',
                                                      'final_score_min': 70,
                                                      'page': 1,
                                                      'per_page': 10}},
                                           {'title': 'Advanced JSON filter: between',
                                            'description': 'Use filters when field/operator/value filtering is '
                                                           'required.',
                                            'path': '/focus/account-intelligence',
                                            'query': {'filters': '[{"field":"final_score","operator":"between","value":[50,100]}]',
                                                      'page': 1,
                                                      'per_page': 10}}],
                              'response_example': {'status': 'success',
                                                   'message': 'LogiKlu account intelligence list fetched successfully',
                                                   'meta': {'generated_at': '2026-07-03T10:00:00+00:00',
                                                            'mode': 'protected',
                                                            'page': 1,
                                                            'per_page': 10,
                                                            'record_count': 1,
                                                            'total_records': 1,
                                                            'total_pages': 1,
                                                            'has_next': False,
                                                            'has_previous': False},
                                                   'data': {'logiklu_focus_account_intelligence': [{'schema_version': 'logiklu_focus_account_intelligence.v1',
                                                                                                    'account': {'account_id': 1094,
                                                                                                                'company_name': 'LogiKlu',
                                                                                                                'company_domain': 'logiklu.com',
                                                                                                                'location': {'country': 'India',
                                                                                                                             'state': 'West '
                                                                                                                                      'Bengal',
                                                                                                                             'city': 'Kolkata'},
                                                                                                                'industry': 'Software'},
                                                                                                    'deterministic_scores': {'score_components': {'activity': 75,
                                                                                                                                                  'sustenance': 30,
                                                                                                                                                  'depth': 55,
                                                                                                                                                  'contextual': 10,
                                                                                                                                                  'conversion': 20,
                                                                                                                                                  'priority': 85},
                                                                                                                             'interest_score': 80,
                                                                                                                             'interest_level': 'High',
                                                                                                                             'priority_label': 'Hot',
                                                                                                                             'final_score': 85},
                                                                                                    'signal_summary': {'session_count': 5,
                                                                                                                       'page_view_count': 29,
                                                                                                                       'total_action_count': 20,
                                                                                                                       'asset_download_count': 7,
                                                                                                                       'external_link_click_count': 7,
                                                                                                                       'form_submission_count': 6},
                                                                                                    'top_evidence_facts': []}]}},
                              'multi_field_filters': [{'name': 'search',
                                                       'example': 'LogiKlu',
                                                       'description': 'General search across company/account fields, '
                                                                      'location, website, industry, contact '
                                                                      'name/email/phone, interest level, priority '
                                                                      'label, and engagement level.'},
                                                      {'name': 'search_by',
                                                       'example': 'contact_email',
                                                       'description': 'Search only one selected field. Example values: '
                                                                      'company_name, website, country, contact_email, '
                                                                      'priority_label, final_score.'},
                                                      {'name': 'account_id',
                                                       'example': '1094',
                                                       'description': 'Filter by exact account ID / lead ID.'},
                                                      {'name': 'lead_id',
                                                       'example': '1094',
                                                       'description': 'Alias for account_id. Filter by exact '
                                                                      'lead/account ID.'},
                                                      {'name': 'company_name',
                                                       'example': 'LogiKlu',
                                                       'description': 'Filter by company/account name.'},
                                                      {'name': 'account_name',
                                                       'example': 'LogiKlu',
                                                       'description': 'Alias for company_name. Filter by account '
                                                                      'name.'},
                                                      {'name': 'lead_name',
                                                       'example': 'LogiKlu',
                                                       'description': 'Filter by CRM lead/account name.'},
                                                      {'name': 'website',
                                                       'example': 'logiklu.com',
                                                       'description': 'Filter by company website/domain.'},
                                                      {'name': 'company_domain',
                                                       'example': 'logiklu.com',
                                                       'description': 'Alias for website. Filter by company domain.'},
                                                      {'name': 'industry',
                                                       'example': 'Software',
                                                       'description': 'Filter by industry. Comma-separated values are '
                                                                      'supported.'},
                                                      {'name': 'city',
                                                       'example': 'Kolkata',
                                                       'description': 'Filter by city.'},
                                                      {'name': 'state',
                                                       'example': 'West Bengal',
                                                       'description': 'Filter by state.'},
                                                      {'name': 'country',
                                                       'example': 'India,Japan',
                                                       'description': 'Filter by one or more countries. '
                                                                      'Comma-separated values are supported.'},
                                                      {'name': 'email',
                                                       'example': 'sales@',
                                                       'description': 'Filter by account/company email.'},
                                                      {'name': 'phone',
                                                       'example': '9876',
                                                       'description': 'Filter by account/company phone.'},
                                                      {'name': 'owner',
                                                       'example': '4',
                                                       'description': 'Filter by account owner user ID where '
                                                                      'available.'},
                                                      {'name': 'lead_category',
                                                       'example': 'lead',
                                                       'description': 'Filter by lead category.'},
                                                      {'name': 'lead_type',
                                                       'example': 'hot',
                                                       'description': 'Filter by lead type/temperature.'},
                                                      {'name': 'lead_status',
                                                       'example': 'active',
                                                       'description': 'Filter by lead status.'},
                                                      {'name': 'active_status',
                                                       'example': 'active',
                                                       'description': 'Filter by active/archive status.'},
                                                      {'name': 'contact_name',
                                                       'example': 'John',
                                                       'description': 'Filter accounts whose linked contacts match '
                                                                      'this name. Uses contact lookup without '
                                                                      'duplicating company rows.'},
                                                      {'name': 'contact_email',
                                                       'example': 'gmail.com',
                                                       'description': 'Filter accounts whose linked contacts match '
                                                                      'this email/domain.'},
                                                      {'name': 'contact_phone',
                                                       'example': '9876',
                                                       'description': 'Filter accounts whose linked contacts match '
                                                                      'this phone number.'},
                                                      {'name': 'interest_level',
                                                       'example': 'High',
                                                       'description': 'Filter by interest level / interest category. '
                                                                      'Comma-separated values are supported.'},
                                                      {'name': 'priority_label',
                                                       'example': 'Hot,Warm',
                                                       'description': 'Filter by priority label such as Hot, Warm, '
                                                                      'Monitor, Low. Comma-separated values are '
                                                                      'supported.'},
                                                      {'name': 'priority_level',
                                                       'example': 'Hot',
                                                       'description': 'Alias for priority_label.'},
                                                      {'name': 'engagement_level',
                                                       'example': 'High',
                                                       'description': 'Filter by engagement level where available.'},
                                                      {'name': 'is_shortlisted',
                                                       'example': 'true',
                                                       'description': 'Filter shortlisted records. Supported values '
                                                                      'include true/false, 1/0, Y/N where '
                                                                      'implemented.'},
                                                      {'name': 'activity_score_min',
                                                       'example': '20',
                                                       'description': 'Minimum activity score.'},
                                                      {'name': 'activity_score_max',
                                                       'example': '80',
                                                       'description': 'Maximum activity score.'},
                                                      {'name': 'depth_score_min',
                                                       'example': '10',
                                                       'description': 'Minimum depth score.'},
                                                      {'name': 'depth_score_max',
                                                       'example': '60',
                                                       'description': 'Maximum depth score.'},
                                                      {'name': 'sustenance_score_min',
                                                       'example': '10',
                                                       'description': 'Minimum sustenance score.'},
                                                      {'name': 'sustenance_score_max',
                                                       'example': '50',
                                                       'description': 'Maximum sustenance score.'},
                                                      {'name': 'sustainment_score_min',
                                                       'example': '10',
                                                       'description': 'Alias for sustenance_score_min.'},
                                                      {'name': 'sustainment_score_max',
                                                       'example': '50',
                                                       'description': 'Alias for sustenance_score_max.'},
                                                      {'name': 'context_score_min',
                                                       'example': '5',
                                                       'description': 'Minimum context score.'},
                                                      {'name': 'context_score_max',
                                                       'example': '30',
                                                       'description': 'Maximum context score.'},
                                                      {'name': 'contextual_score_min',
                                                       'example': '5',
                                                       'description': 'Alias for context_score_min.'},
                                                      {'name': 'contextual_score_max',
                                                       'example': '30',
                                                       'description': 'Alias for context_score_max.'},
                                                      {'name': 'conversion_score_min',
                                                       'example': '0',
                                                       'description': 'Minimum conversion score.'},
                                                      {'name': 'conversion_score_max',
                                                       'example': '100',
                                                       'description': 'Maximum conversion score.'},
                                                      {'name': 'interest_score_min',
                                                       'example': '25',
                                                       'description': 'Minimum interest score.'},
                                                      {'name': 'interest_score_max',
                                                       'example': '100',
                                                       'description': 'Maximum interest score.'},
                                                      {'name': 'priority_score_min',
                                                       'example': '50',
                                                       'description': 'Minimum priority score.'},
                                                      {'name': 'priority_score_max',
                                                       'example': '100',
                                                       'description': 'Maximum priority score.'},
                                                      {'name': 'final_score_min',
                                                       'example': '50',
                                                       'description': 'Minimum final score.'},
                                                      {'name': 'final_score_max',
                                                       'example': '100',
                                                       'description': 'Maximum final score.'},
                                                      {'name': 'total_score_min',
                                                       'example': '50',
                                                       'description': 'Alias for final_score_min / total score '
                                                                      'minimum.'},
                                                      {'name': 'total_score_max',
                                                       'example': '100',
                                                       'description': 'Alias for final_score_max / total score '
                                                                      'maximum.'}],
                              'search_by_options': [{'name': 'company_name',
                                                     'example': 'LogiKlu',
                                                     'description': 'Search company/account name only.'},
                                                    {'name': 'account_name',
                                                     'example': 'LogiKlu',
                                                     'description': 'Search account name only.'},
                                                    {'name': 'lead_name',
                                                     'example': 'LogiKlu',
                                                     'description': 'Search CRM lead/account name only.'},
                                                    {'name': 'website',
                                                     'example': 'logiklu.com',
                                                     'description': 'Search website/domain only.'},
                                                    {'name': 'company_domain',
                                                     'example': 'logiklu.com',
                                                     'description': 'Search company domain only.'},
                                                    {'name': 'industry',
                                                     'example': 'Software',
                                                     'description': 'Search industry only.'},
                                                    {'name': 'city',
                                                     'example': 'Kolkata',
                                                     'description': 'Search city only.'},
                                                    {'name': 'state',
                                                     'example': 'West Bengal',
                                                     'description': 'Search state only.'},
                                                    {'name': 'country',
                                                     'example': 'India',
                                                     'description': 'Search country only.'},
                                                    {'name': 'email',
                                                     'example': 'sales@',
                                                     'description': 'Search account email only.'},
                                                    {'name': 'phone',
                                                     'example': '9876',
                                                     'description': 'Search account phone only.'},
                                                    {'name': 'contact_name',
                                                     'example': 'John',
                                                     'description': 'Search linked contact name only.'},
                                                    {'name': 'contact_email',
                                                     'example': 'gmail.com',
                                                     'description': 'Search linked contact email only.'},
                                                    {'name': 'contact_phone',
                                                     'example': '9876',
                                                     'description': 'Search linked contact phone only.'},
                                                    {'name': 'interest_level',
                                                     'example': 'High',
                                                     'description': 'Search/filter interest level only.'},
                                                    {'name': 'priority_label',
                                                     'example': 'Hot',
                                                     'description': 'Search/filter priority label only.'},
                                                    {'name': 'engagement_level',
                                                     'example': 'High',
                                                     'description': 'Search/filter engagement level only.'},
                                                    {'name': 'final_score',
                                                     'example': '75',
                                                     'description': 'Search/filter final score, usually better handled '
                                                                    'with final_score_min/final_score_max.'}]},
                             {'id': 'focus-account-intelligence-detail',
                              'title': 'Focus Account Intelligence Details',
                              'method': 'GET',
                              'path': '/focus/account-intelligence/{account_id}',
                              'purpose': 'Fetch one account intelligence record by account ID with score, signal '
                                         'summary, evidence, contacts, and journey intelligence.',
                              'auth_type': 'bearer',
                              'request_type': 'Path Parameter',
                              'parameters': [{'name': 'account_id',
                                              'type': 'integer',
                                              'required': 'Yes',
                                              'example': '1094',
                                              'description': 'Account ID / lead ID for which Focus intelligence should '
                                                             'be fetched.'}],
                              'examples': [{'title': 'Get one Focus Account Intelligence record',
                                            'description': 'Use this when you already know the account ID.',
                                            'path': '/focus/account-intelligence/1094',
                                            'query': {}}],
                              'response_example': {'status': 'success',
                                                   'message': 'Focus Account Intelligence fetched successfully',
                                                   'meta': {'generated_at': '2026-07-03T10:00:00+00:00',
                                                            'account_id': 1094},
                                                   'data': {'logiklu_account_inetellegence': {'schema_version': 'logiklu_focus_account_intelligence.v1',
                                                                                              'account': {'account_id': 1094,
                                                                                                          'company_name': 'LogiKlu'},
                                                                                              'signal_summary': {},
                                                                                              'top_evidence_facts': []}}}}]}],
 'errors': [{'code': 'AUTH_CREDENTIALS_MISSING',
             'http_status': 401,
             'meaning': 'No bearer token was sent.',
             'fix': 'Generate a token using /oauth/token and send Authorization: Bearer <access_token>.'},
            {'code': 'AUTHORIZATION_HEADER_INVALID',
             'http_status': 401,
             'meaning': 'Authorization header was sent in an invalid format.',
             'fix': 'Use Authorization: Bearer <access_token>.'},
            {'code': 'OAUTH_INVALID_CLIENT',
             'http_status': 401,
             'meaning': 'The client_id is invalid or not found.',
             'fix': 'Check the client_id provided by LogiKlu.'},
            {'code': 'OAUTH_INVALID_CLIENT_SECRET',
             'http_status': 401,
             'meaning': 'The client_secret is invalid.',
             'fix': 'Check the client_secret provided by LogiKlu.'},
            {'code': 'OAUTH_UNSUPPORTED_GRANT_TYPE',
             'http_status': 400,
             'meaning': 'The grant_type is not supported.',
             'fix': 'Use grant_type=client_credentials.'},
            {'code': 'AUTH_JWT_INVALID',
             'http_status': 401,
             'meaning': 'The bearer token is malformed or invalid.',
             'fix': 'Generate a fresh token from /oauth/token and retry.'},
            {'code': 'AUTH_JWT_EXPIRED',
             'http_status': 401,
             'meaning': 'The bearer token has expired.',
             'fix': 'Generate a fresh token from /oauth/token.'},
            {'code': 'AUTH_JWT_AUDIENCE_INVALID',
             'http_status': 401,
             'meaning': 'The bearer token audience does not match this API environment.',
             'fix': 'Use a token generated for the correct environment.'},
            {'code': 'AUTH_JWT_ENVIRONMENT_MISMATCH',
             'http_status': 401,
             'meaning': 'The bearer token was generated for a different environment.',
             'fix': 'Use sandbox tokens only on sandbox and production tokens only on production.'},
            {'code': 'LOGIKLU_ACCOUNT_INTELLIGENCE_NOT_FOUND',
             'http_status': 404,
             'meaning': 'No LogiKlu account intelligence record was found for the requested account_id.',
             'fix': 'Use a valid account_id available in the current LogiKlu Focus intelligence dataset.'},
            {'code': 'VALIDATION_ERROR',
             'http_status': 422,
             'meaning': 'One or more request parameters are invalid.',
             'fix': 'Check parameter names, types, and allowed values.'},
            {'code': 'INTERNAL_SERVER_ERROR',
             'http_status': 500,
             'meaning': 'Unexpected server-side error.',
             'fix': 'Retry later or contact LogiKlu technical support with request details.'}],
 'logging': {'title': 'API Request Logging',
             'description': 'LogiKlu stores API request logs internally for audit, troubleshooting, and support.',
             'logged_fields': ['oauth_client_id',
                               'auth_type',
                               'api_client_id',
                               'domain_id',
                               'client_database',
                               'environment',
                               'endpoint',
                               'request_method',
                               'ip_address',
                               'user_agent',
                               'request_params',
                               'http_status_code',
                               'response_status',
                               'error_code',
                               'error_message',
                               'execution_time_ms',
                               'created_at'],
             'sandbox_table': 'lk_agent_api_request_logs_sandbox',
             'production_table': 'lk_agent_api_request_logs'}}
