# Internal master usage data.
# This file is rendered by /masterusage and should remain password protected.
# Do not expose this file or page to external clients.

API_USAGE_MASTER_DATA = {'title': 'LogiKlu Agent API Master Guide',
 'subtitle': 'Internal developer guide for LogiKlu API endpoints. This page is password protected and must not be '
             'shared with external clients.',
 'base_url': 'https://api.logiklu.com',
 'sandbox_base_url': 'https://sandboxapi.logiklu.com',
 'local_base_url': 'http://127.0.0.1:8000',
 'api_version': 'v1',
 'auth': {'title': 'Authentication',
          'description': 'Protected APIs use OAuth 2.0 Client Credentials with a short-lived Bearer JWT. First '
                         'generate an access token from /oauth/token, then send it in the Authorization header.',
          'headers': [{'name': 'Authorization',
                       'required': 'Yes',
                       'description': 'Use Bearer authentication for protected APIs. Format: Authorization: Bearer '
                                      '<access_token>.'}],
          'token_endpoint': {'method': 'POST',
                             'path': '/oauth/token',
                             'auth': 'No Auth',
                             'content_type': 'application/json',
                             'description': 'Generate a short-lived access token using the OAuth client credentials '
                                            'flow.',
                             'request_body': {'client_id': 'Provided OAuth client ID. This is '
                                                           'lk_agent_api_clients.oauth_client_id.',
                                              'client_secret': 'Provided client secret. Keep this private.',
                                              'grant_type': 'client_credentials'},
                             'response_fields': {'access_token': 'JWT access token to be sent as Bearer token.',
                                                 'token_type': 'Bearer',
                                                 'expires_in': 'Token lifetime in seconds. Current default is 900 '
                                                               'seconds.',
                                                 'scope': 'Allowed API permissions/scopes.'}}},
 'response_format': {'success': {'status': 'success',
                                 'message': 'Accounts fetched successfully',
                                 'meta': {'generated_at': '2026-05-27T10:00:00+00:00',
                                          'limit': 20,
                                          'offset': 0,
                                          'search': None,
                                          'search_by': None,
                                          'applied_filters': [{'field': 'country',
                                                               'operator': 'like',
                                                               'value': 'India'}],
                                          'record_count': 20,
                                          'total_records': 357},
                                 'data': {}},
                     'error': {'status': 'error',
                               'message': 'Missing bearer token',
                               'error_code': 'AUTH_CREDENTIALS_MISSING',
                               'meta': {'timestamp': '2026-05-27T10:00:00+00:00'},
                               'data': None}},
 'notes': [{'title': 'JWT Bearer authentication only',
            'description': 'Master usage examples use Authorization: Bearer <access_token>. The token is generated '
                           'from /oauth/token using OAuth client credentials.'},
           {'title': 'OAuth token flow',
            'description': 'Call /oauth/token with client_id, client_secret, and grant_type=client_credentials. Then '
                           'send the returned access_token as Authorization: Bearer <access_token>.'},
           {'title': 'Bearer token expiry',
            'description': 'Access tokens are short-lived. The current default expiry is 900 seconds. Generate a new '
                           'token when the previous token expires.'},
           {'title': 'No JWT secret sharing',
            'description': 'JWT_SECRET_KEY is an internal LogiKlu server secret. It must never be shared with API '
                           'consumers.'},
           {'title': 'Clean endpoint paths',
            'description': 'Public API routes use clean paths such as /accounts, /contacts, /oauth/token, and '
                           '/focus/account-intelligence. Do not prefix these routes with /api/v1.'},
           {'title': 'Multi-field filters',
            'description': 'List APIs support direct query-parameter filters. Example: '
                           '/accounts?country=India&industry=Software. Multiple filters are combined using AND logic.'},
           {'title': 'Comma-separated values',
            'description': 'Some filters support comma-separated values. Example: /accounts?country=India,Japan.'},
           {'title': 'Advanced JSON filters',
            'description': 'The filters parameter is still supported for advanced field/operator/value filtering.'},
           {'title': 'API logging',
            'description': 'API requests are logged internally. Sandbox and production logs are stored separately.'},
           {'title': 'Standard errors',
            'description': 'Authentication errors, validation errors, not-found errors, method errors, and server '
                           'errors follow the same standard response format.'},
           {'title': 'Master documentation',
            'description': 'This page contains internal and backward-compatible API details. Public/client '
                           'documentation should be maintained separately in api_usage_data.py.'}],
 'sections': [{'id': 'authentication',
               'title': 'OAuth / JWT Authentication',
               'description': 'Generate a short-lived access token using /oauth/token. Then call protected APIs using '
                              'Authorization: Bearer <access_token>.',
               'endpoints': [{'id': 'oauth-token',
                              'title': 'Generate Access Token',
                              'method': 'POST',
                              'path': '/oauth/token',
                              'purpose': 'Generate a Bearer access token using OAuth client credentials. This endpoint '
                                         'uses No Auth.',
                              'request_type': 'JSON Body',
                              'parameters': [{'name': 'client_id',
                                              'required': 'Yes',
                                              'example': 'lkc_3f2a6a9eae2c4b2db37f9875f0e9a111',
                                              'description': 'OAuth client ID provided by LogiKlu. This maps to '
                                                             'lk_agent_api_clients.oauth_client_id.'},
                                             {'name': 'client_secret',
                                              'required': 'Yes',
                                              'example': 'provided_client_secret',
                                              'description': 'Client secret provided by LogiKlu. Keep this private and '
                                                             'never expose it in frontend code.'},
                                             {'name': 'grant_type',
                                              'required': 'Yes',
                                              'example': 'client_credentials',
                                              'description': 'Must be client_credentials.'}],
                              'examples': [{'title': 'Generate token',
                                            'description': 'Call this endpoint with No Auth. Use the returned '
                                                           'access_token as Bearer token for protected APIs.',
                                            'path': '/oauth/token',
                                            'body': {'client_id': 'YOUR_CLIENT_ID',
                                                     'client_secret': 'YOUR_CLIENT_SECRET',
                                                     'grant_type': 'client_credentials'},
                                            'query': {}}],
                              'auth_type': 'none',
                              'body': {'client_id': 'YOUR_CLIENT_ID',
                                       'client_secret': 'YOUR_CLIENT_SECRET',
                                       'grant_type': 'client_credentials'}}]},
              {'id': 'focus-account-intelligence',
               'title': 'Focus Account Intelligence',
               'description': 'Use Focus Account Intelligence APIs to read LogiKlu Focus buying-intent signals, '
                              'priority score, interest level, evidence facts, contacts, and journey intelligence for '
                              'accounts.',
               'endpoints': [{'id': 'focus-account-intelligence-list',
                              'title': 'Focus Account Intelligence List',
                              'method': 'GET',
                              'path': '/focus/account-intelligence',
                              'purpose': 'Fetch Focus Account Intelligence records with search, filters, pagination, '
                                         'signal summary, and journey intelligence. The actual protected API includes '
                                         'journey data by default. Preferred authentication: Authorization Bearer '
                                         'token.',
                              'request_type': 'Query Parameters',
                              'parameters': [{'name': 'page',
                                              'required': 'No',
                                              'example': '1',
                                              'description': 'Page number. Default is 1.'},
                                             {'name': 'per_page',
                                              'required': 'No',
                                              'example': '10',
                                              'description': 'Number of records per page.'},
                                             {'name': 'search',
                                              'required': 'No',
                                              'example': 'LogiKlu',
                                              'description': 'Search by account/company name, website, city, state, '
                                                             'country, or related searchable values.'},
                                             {'name': 'interest_level',
                                              'required': 'No',
                                              'example': 'High',
                                              'description': 'Filter by interest level when available. Example values '
                                                             'depend on the Focus scoring output.'},
                                             {'name': 'priority_label',
                                              'required': 'No',
                                              'example': 'Hot',
                                              'description': 'Filter by priority label such as Hot, Warm, Monitor, or '
                                                             'Low when available.'},
                                             {'name': 'is_shortlisted',
                                              'required': 'No',
                                              'example': 'true',
                                              'description': 'Filter shortlisted records. Supported values depend on '
                                                             'implementation, usually true/false or 1/0.'}],
                              'examples': [{'title': 'Get first page of Focus Account Intelligence',
                                            'description': 'Use this to retrieve the first page of account '
                                                           'intelligence records.',
                                            'path': '/focus/account-intelligence',
                                            'query': {'page': 1, 'per_page': 10}},
                                           {'title': 'Search Focus Account Intelligence',
                                            'description': 'Search Focus intelligence records by account-related text.',
                                            'path': '/focus/account-intelligence',
                                            'query': {'search': 'LogiKlu', 'page': 1, 'per_page': 10}},
                                           {'title': 'Filter by priority',
                                            'description': 'Fetch records matching a priority label.',
                                            'path': '/focus/account-intelligence',
                                            'query': {'priority_label': 'Hot', 'page': 1, 'per_page': 10}}],
                              'auth_type': 'bearer'},
                             {'id': 'focus-account-intelligence-detail',
                              'title': 'Focus Account Intelligence Details',
                              'method': 'GET',
                              'path': '/focus/account-intelligence/{account_id}',
                              'purpose': 'Fetch one account intelligence record by account ID with score, signal '
                                         'summary, evidence, contacts, and journey intelligence. Preferred '
                                         'authentication: Authorization Bearer token.',
                              'request_type': 'Path Parameter',
                              'parameters': [{'name': 'account_id',
                                              'required': 'Yes',
                                              'example': '1094',
                                              'description': 'Account ID / lead ID for which Focus intelligence should '
                                                             'be fetched.'}],
                              'examples': [{'title': 'Get one Focus Account Intelligence record',
                                            'description': 'Use this when you already know the account ID.',
                                            'path': '/focus/account-intelligence/1094',
                                            'query': {}}],
                              'auth_type': 'bearer'}]},
              {'id': 'accounts',
               'title': 'Accounts',
               'description': 'Use Account APIs to read company/account information from LogiKlu CRM.',
               'endpoints': [{'id': 'account-list',
                              'title': 'Account List',
                              'method': 'GET',
                              'path': '/accounts',
                              'purpose': 'Fetch account records with general search, multi-field filters, pagination, '
                                         'contacts, and dynamic account fields.',
                              'request_type': 'Query Parameters',
                              'parameters': [{'name': 'limit',
                                              'required': 'No',
                                              'example': '20',
                                              'description': 'Number of records to return. Maximum value is 100.'},
                                             {'name': 'offset',
                                              'required': 'No',
                                              'example': '0',
                                              'description': 'Pagination offset.'},
                                             {'name': 'search',
                                              'required': 'No',
                                              'example': 'Hamamatsu',
                                              'description': 'General search value. If search_by is empty, this '
                                                             'searches common account fields.'},
                                             {'name': 'search_by',
                                              'required': 'No',
                                              'example': 'lead_name',
                                              'description': 'Optional old-style specific field search. Example: '
                                                             'lead_name, country, owner, assigned_to.'},
                                             {'name': 'lead_publish_status',
                                              'required': 'No',
                                              'example': 'active',
                                              'description': 'Allowed values: active, archive, all.'},
                                             {'name': 'computed_lead_category',
                                              'required': 'No',
                                              'example': 'lead',
                                              'description': 'Allowed values: all, lead, potential_lead, customer.'},
                                             {'name': 'filters',
                                              'required': 'No',
                                              'example': '[{"field":"country","operator":"eq","value":"Japan"}]',
                                              'description': 'Advanced JSON filters. Use this when operator-level '
                                                             'filtering is needed.'}],
                              'multi_field_filters': [{'name': 'account_id',
                                                       'example': '9626',
                                                       'description': 'Exact account ID.'},
                                                      {'name': 'lead_name',
                                                       'example': 'LogiKlu',
                                                       'description': 'Filter by account name.'},
                                                      {'name': 'lead_segment',
                                                       'example': 'company',
                                                       'description': 'Filter by lead segment.'},
                                                      {'name': 'lead_category',
                                                       'example': 'lead',
                                                       'description': 'Filter by raw lead category.'},
                                                      {'name': 'lead_type',
                                                       'example': 'hot',
                                                       'description': 'Filter by lead temperature/type.'},
                                                      {'name': 'lead_status_id',
                                                       'example': '1',
                                                       'description': 'Filter by lead status ID.'},
                                                      {'name': 'lead_status_name',
                                                       'example': 'New',
                                                       'description': 'Filter by lead status name.'},
                                                      {'name': 'website',
                                                       'example': 'logiklu.com',
                                                       'description': 'Filter by website/domain.'},
                                                      {'name': 'email',
                                                       'example': 'sales@',
                                                       'description': 'Filter by account email.'},
                                                      {'name': 'phone',
                                                       'example': '9876',
                                                       'description': 'Filter by account phone.'},
                                                      {'name': 'industry',
                                                       'example': 'Software',
                                                       'description': 'Filter by industry.'},
                                                      {'name': 'city',
                                                       'example': 'Kolkata',
                                                       'description': 'Filter by city.'},
                                                      {'name': 'state',
                                                       'example': 'West Bengal',
                                                       'description': 'Filter by state.'},
                                                      {'name': 'country',
                                                       'example': 'India,Japan',
                                                       'description': 'Filter by one or multiple countries.'},
                                                      {'name': 'zipcode',
                                                       'example': '700001',
                                                       'description': 'Filter by zipcode.'},
                                                      {'name': 'source',
                                                       'example': 'website,manual,csv',
                                                       'description': 'Filter by one or multiple source values.'},
                                                      {'name': 'lead_source',
                                                       'example': 'LinkedIn',
                                                       'description': 'Filter by lead source.'},
                                                      {'name': 'owner',
                                                       'example': '4',
                                                       'description': 'Filter by owner user ID.'},
                                                      {'name': 'created_by',
                                                       'example': '4',
                                                       'description': 'Filter by creator user ID.'},
                                                      {'name': 'modified_by',
                                                       'example': '4',
                                                       'description': 'Filter by modifier user ID.'}],
                              'search_by_options': [{'name': 'lead_name',
                                                     'example': 'Hamamatsu',
                                                     'description': 'Search account name.'},
                                                    {'name': 'lead_segment',
                                                     'example': 'Company',
                                                     'description': 'Company maps to company. Contact maps to '
                                                                    'contact.'},
                                                    {'name': 'lead_category',
                                                     'example': 'Lead',
                                                     'description': 'Potential Lead maps to suspect. Lead maps to '
                                                                    'lead.'},
                                                    {'name': 'lead_type',
                                                     'example': 'hot,warm,cold',
                                                     'description': 'Search one or multiple lead types.'},
                                                    {'name': 'lead_persuing_status',
                                                     'example': '1,2,3',
                                                     'description': 'Search one or multiple lead status IDs.'},
                                                    {'name': 'website',
                                                     'example': 'logiklu.com',
                                                     'description': 'Search website/domain.'},
                                                    {'name': 'email',
                                                     'example': 'sales@',
                                                     'description': 'Search account email.'},
                                                    {'name': 'phone',
                                                     'example': '9876',
                                                     'description': 'Search account phone.'},
                                                    {'name': 'industry',
                                                     'example': 'Software',
                                                     'description': 'Search industry.'},
                                                    {'name': 'city',
                                                     'example': 'Kolkata',
                                                     'description': 'Search city.'},
                                                    {'name': 'state',
                                                     'example': 'West Bengal',
                                                     'description': 'Search state.'},
                                                    {'name': 'country',
                                                     'example': 'India,Japan',
                                                     'description': 'Search one or multiple countries.'},
                                                    {'name': 'zipcode',
                                                     'example': '700001',
                                                     'description': 'Search zipcode.'},
                                                    {'name': 'employee_count',
                                                     'example': '100',
                                                     'description': 'Search employee lower/upper range.'},
                                                    {'name': 'owner',
                                                     'example': '4,8,12',
                                                     'description': 'Search one or multiple owner user IDs.'},
                                                    {'name': 'created_by',
                                                     'example': '4,8',
                                                     'description': 'Search one or multiple creator user IDs.'},
                                                    {'name': 'source',
                                                     'example': 'website,manual,csv',
                                                     'description': 'Search one or multiple source values.'},
                                                    {'name': 'lead_source',
                                                     'example': 'LinkedIn,Event',
                                                     'description': 'Search one or multiple lead source values.'},
                                                    {'name': 'assigned_to',
                                                     'example': '4,8,12',
                                                     'description': 'Search assigned user IDs from lk_lead_assign.'}],
                              'examples': [{'title': 'Get first 20 active accounts',
                                            'description': 'Use this to get the first page of active accounts.',
                                            'path': '/accounts',
                                            'query': {'limit': 20, 'offset': 0}},
                                           {'title': 'General account search',
                                            'description': 'Search common account fields using one search value.',
                                            'path': '/accounts',
                                            'query': {'search': 'Japan', 'limit': 20, 'offset': 0}},
                                           {'title': 'Multi-field account filter',
                                            'description': 'Filter accounts using multiple direct query parameters.',
                                            'path': '/accounts',
                                            'query': {'country': 'India', 'industry': 'Software', 'limit': 20}},
                                           {'title': 'Multi-value country filter',
                                            'description': 'Filter accounts from one or more countries.',
                                            'path': '/accounts',
                                            'query': {'country': 'India,Japan', 'limit': 20}},
                                           {'title': 'Search by account name',
                                            'description': 'Search only the account name field using old search_by '
                                                           'style.',
                                            'path': '/accounts',
                                            'query': {'search': 'Hamamatsu',
                                                      'search_by': 'lead_name',
                                                      'limit': 20,
                                                      'offset': 0}},
                                           {'title': 'Get only Lead accounts',
                                            'description': 'Lead means raw category is lead and the account has active '
                                                           'contacts.',
                                            'path': '/accounts',
                                            'query': {'computed_lead_category': 'lead', 'limit': 20, 'offset': 0}},
                                           {'title': 'Get only Potential Lead accounts',
                                            'description': 'Potential Lead means suspect, or lead with no active '
                                                           'contacts.',
                                            'path': '/accounts',
                                            'query': {'computed_lead_category': 'potential_lead',
                                                      'limit': 20,
                                                      'offset': 0}},
                                           {'title': 'Advanced JSON filter',
                                            'description': 'Use filters for field/operator/value search.',
                                            'path': '/accounts',
                                            'query': {'filters': '[{"field":"country","operator":"eq","value":"Japan"}]'}}],
                              'auth_type': 'bearer'},
                             {'id': 'account-detail',
                              'title': 'Account Details',
                              'method': 'GET',
                              'path': '/accounts/{account_id}',
                              'purpose': 'Fetch one account by account ID with dynamic fields and contacts.',
                              'request_type': 'Path Parameter',
                              'parameters': [{'name': 'account_id',
                                              'required': 'Yes',
                                              'example': '9626',
                                              'description': 'Unique account ID from lk_lead_master.lead_id.'}],
                              'examples': [{'title': 'Get one account detail',
                                            'description': 'Use this when you already know the account ID.',
                                            'path': '/accounts/9626',
                                            'query': {}}],
                              'auth_type': 'bearer'}]},
              {'id': 'contacts',
               'title': 'Contacts',
               'description': 'Use Contact APIs to read people/contact information from LogiKlu CRM.',
               'endpoints': [{'id': 'contact-list',
                              'title': 'Contact List',
                              'method': 'GET',
                              'path': '/contacts',
                              'purpose': 'Fetch contacts with general search, multi-field filters, account search, '
                                         'dynamic fields, and linked account summary.',
                              'request_type': 'Query Parameters',
                              'parameters': [{'name': 'limit',
                                              'required': 'No',
                                              'example': '50',
                                              'description': 'Number of records to return. Maximum value is 100.'},
                                             {'name': 'offset',
                                              'required': 'No',
                                              'example': '0',
                                              'description': 'Pagination offset.'},
                                             {'name': 'search',
                                              'required': 'No',
                                              'example': 'Manager',
                                              'description': 'General search value. If search_by is empty, this '
                                                             'searches common contact fields.'},
                                             {'name': 'search_by',
                                              'required': 'No',
                                              'example': 'designation',
                                              'description': 'Optional old-style specific contact field search.'},
                                             {'name': 'account_id',
                                              'required': 'No',
                                              'example': '1094',
                                              'description': 'Fetch contacts under a specific account.'},
                                             {'name': 'account_search',
                                              'required': 'No',
                                              'example': 'LogiKlu',
                                              'description': 'Search contacts by account ID, account name, or account '
                                                             'website.'},
                                             {'name': 'associated_accounts_only',
                                              'required': 'No',
                                              'example': 'true',
                                              'description': 'If true, only contacts linked with accounts are '
                                                             'returned.'},
                                             {'name': 'filters',
                                              'required': 'No',
                                              'example': '[{"field":"country","operator":"eq","value":"India"}]',
                                              'description': 'Advanced JSON filters. Use this when operator-level '
                                                             'filtering is needed.'}],
                              'multi_field_filters': [{'name': 'name',
                                                       'example': 'John',
                                                       'description': 'Filter by first name, last name, or full name.'},
                                                      {'name': 'first_name',
                                                       'example': 'John',
                                                       'description': 'Filter by first name.'},
                                                      {'name': 'last_name',
                                                       'example': 'Smith',
                                                       'description': 'Filter by last name.'},
                                                      {'name': 'email',
                                                       'example': 'gmail.com',
                                                       'description': 'Filter by email.'},
                                                      {'name': 'phone',
                                                       'example': '9876',
                                                       'description': 'Filter by primary phone.'},
                                                      {'name': 'whatsapp',
                                                       'example': '9876',
                                                       'description': 'Filter by WhatsApp number.'},
                                                      {'name': 'alternative_phone',
                                                       'example': '9876',
                                                       'description': 'Filter by alternative phone.'},
                                                      {'name': 'alternative_emails',
                                                       'example': 'sales@',
                                                       'description': 'Filter by alternative emails.'},
                                                      {'name': 'address',
                                                       'example': 'Park Street',
                                                       'description': 'Filter by address.'},
                                                      {'name': 'city',
                                                       'example': 'Kolkata',
                                                       'description': 'Filter by city.'},
                                                      {'name': 'state',
                                                       'example': 'West Bengal',
                                                       'description': 'Filter by state.'},
                                                      {'name': 'country',
                                                       'example': 'India,Japan',
                                                       'description': 'Filter by one or multiple countries.'},
                                                      {'name': 'zipcode',
                                                       'example': '700001',
                                                       'description': 'Filter by zipcode.'},
                                                      {'name': 'department',
                                                       'example': 'Marketing',
                                                       'description': 'Filter by department.'},
                                                      {'name': 'designation',
                                                       'example': 'Manager',
                                                       'description': 'Filter by job title/designation.'},
                                                      {'name': 'contact_type',
                                                       'example': 'contact',
                                                       'description': 'Filter by contact type.'},
                                                      {'name': 'source',
                                                       'example': 'website,manual,csv',
                                                       'description': 'Filter by one or multiple source values.'},
                                                      {'name': 'owner',
                                                       'example': '4',
                                                       'description': 'Filter by owner user ID.'},
                                                      {'name': 'created_by',
                                                       'example': '4',
                                                       'description': 'Filter by creator user ID.'},
                                                      {'name': 'modified_by',
                                                       'example': '4',
                                                       'description': 'Filter by modifier user ID.'}],
                              'search_by_options': [{'name': 'name',
                                                     'example': 'John',
                                                     'description': 'Search first name, last name, and full name.'},
                                                    {'name': 'first_name',
                                                     'example': 'John',
                                                     'description': 'Search first name.'},
                                                    {'name': 'last_name',
                                                     'example': 'Smith',
                                                     'description': 'Search last name.'},
                                                    {'name': 'email',
                                                     'example': 'gmail.com',
                                                     'description': 'Search email.'},
                                                    {'name': 'phone',
                                                     'example': '9876',
                                                     'description': 'Search primary phone.'},
                                                    {'name': 'whatsapp',
                                                     'example': '9876',
                                                     'description': 'Search WhatsApp number.'},
                                                    {'name': 'alternative_phone',
                                                     'example': '9876',
                                                     'description': 'Search alternative phone.'},
                                                    {'name': 'alternative_emails',
                                                     'example': 'sales@',
                                                     'description': 'Search alternative emails.'},
                                                    {'name': 'address',
                                                     'example': 'Park Street',
                                                     'description': 'Search address.'},
                                                    {'name': 'city',
                                                     'example': 'Kolkata',
                                                     'description': 'Search city.'},
                                                    {'name': 'state',
                                                     'example': 'West Bengal',
                                                     'description': 'Search state.'},
                                                    {'name': 'country',
                                                     'example': 'India,Japan',
                                                     'description': 'Search one or multiple countries.'},
                                                    {'name': 'zipcode',
                                                     'example': '700001',
                                                     'description': 'Search zipcode.'},
                                                    {'name': 'department',
                                                     'example': 'Marketing',
                                                     'description': 'Search department.'},
                                                    {'name': 'designation',
                                                     'example': 'Manager',
                                                     'description': 'Search job title/designation.'},
                                                    {'name': 'contact_type',
                                                     'example': 'contact,guest',
                                                     'description': 'Search one or multiple contact types.'},
                                                    {'name': 'source',
                                                     'example': 'website,manual,csv',
                                                     'description': 'Search one or multiple source values.'},
                                                    {'name': 'owner',
                                                     'example': '4,8,12',
                                                     'description': 'Search one or multiple owner user IDs.'},
                                                    {'name': 'created_by',
                                                     'example': '4,8',
                                                     'description': 'Search one or multiple creator user IDs.'},
                                                    {'name': 'modified_by',
                                                     'example': '4,8',
                                                     'description': 'Search one or multiple modifier user IDs.'}],
                              'examples': [{'title': 'Get first 50 contacts',
                                            'description': 'Use this to get the first page of contacts.',
                                            'path': '/contacts',
                                            'query': {'limit': 50, 'offset': 0}},
                                           {'title': 'General contact search',
                                            'description': 'Search common contact fields.',
                                            'path': '/contacts',
                                            'query': {'search': 'manager'}},
                                           {'title': 'Multi-field contact filter',
                                            'description': 'Filter contacts using multiple direct query parameters.',
                                            'path': '/contacts',
                                            'query': {'country': 'India', 'department': 'Sales', 'limit': 20}},
                                           {'title': 'Multi-value country filter',
                                            'description': 'Filter contacts from one or more countries.',
                                            'path': '/contacts',
                                            'query': {'country': 'India,Japan', 'limit': 20}},
                                           {'title': 'Search by contact name',
                                            'description': 'Search first name, last name, and full name using old '
                                                           'search_by style.',
                                            'path': '/contacts',
                                            'query': {'search': 'John', 'search_by': 'name'}},
                                           {'title': 'Search by email',
                                            'description': 'Search contacts by email.',
                                            'path': '/contacts',
                                            'query': {'search': 'gmail.com', 'search_by': 'email'}},
                                           {'title': 'Contacts under one account',
                                            'description': 'Fetch contacts linked with one account ID.',
                                            'path': '/contacts',
                                            'query': {'account_id': 1094}},
                                           {'title': 'Search by account',
                                            'description': 'Search contacts by account ID, account name, or account '
                                                           'website.',
                                            'path': '/contacts',
                                            'query': {'account_search': 'LogiKlu'}},
                                           {'title': 'Only contacts linked to accounts',
                                            'description': 'Use this when you do not want standalone/unlinked '
                                                           'contacts.',
                                            'path': '/contacts',
                                            'query': {'associated_accounts_only': 'true'}},
                                           {'title': 'Advanced JSON filter',
                                            'description': 'Use filters for field/operator/value search.',
                                            'path': '/contacts',
                                            'query': {'filters': '[{"field":"country","operator":"eq","value":"India"}]'}}],
                              'auth_type': 'bearer'},
                             {'id': 'contact-detail',
                              'title': 'Contact Details',
                              'method': 'GET',
                              'path': '/contacts/{contact_id}',
                              'purpose': 'Fetch one contact by contact ID with dynamic fields and linked account '
                                         'summary.',
                              'request_type': 'Path Parameter',
                              'parameters': [{'name': 'contact_id',
                                              'required': 'Yes',
                                              'example': '101',
                                              'description': 'Unique contact ID from lk_central_contacts.contact_id.'}],
                              'examples': [{'title': 'Get one contact detail',
                                            'description': 'Use this when you already know the contact ID.',
                                            'path': '/contacts/101',
                                            'query': {}}],
                              'auth_type': 'bearer'}]}],
 'errors': [{'code': 'AUTH_CREDENTIALS_MISSING',
             'http_status': 401,
             'meaning': 'No bearer token was sent.',
             'fix': 'Generate an access token from /oauth/token and send Authorization: Bearer <access_token>.'},
            {'code': 'AUTHORIZATION_HEADER_INVALID',
             'http_status': 401,
             'meaning': 'Authorization header was sent in an invalid format.',
             'fix': 'Use Authorization: Bearer <access_token>.'},
            {'code': 'OAUTH_INVALID_CLIENT',
             'http_status': 401,
             'meaning': 'The client_id is invalid or not found.',
             'fix': 'Check the client_id provided by LogiKlu.'},
            {'code': 'OAUTH_INVALID_CLIENT_SECRET',
             'http_status': 401,
             'meaning': 'The client_secret is invalid.',
             'fix': 'Check the client_secret provided by LogiKlu.'},
            {'code': 'OAUTH_UNSUPPORTED_GRANT_TYPE',
             'http_status': 400,
             'meaning': 'The grant_type is not supported.',
             'fix': 'Use grant_type=client_credentials.'},
            {'code': 'AUTH_JWT_INVALID',
             'http_status': 401,
             'meaning': 'The bearer token is malformed or invalid.',
             'fix': 'Generate a fresh token from /oauth/token and retry.'},
            {'code': 'AUTH_JWT_EXPIRED',
             'http_status': 401,
             'meaning': 'The bearer token has expired.',
             'fix': 'Generate a fresh token from /oauth/token.'},
            {'code': 'AUTH_JWT_AUDIENCE_INVALID',
             'http_status': 401,
             'meaning': 'The bearer token audience does not match this API environment.',
             'fix': 'Use a token generated for the correct environment.'},
            {'code': 'AUTH_JWT_ENVIRONMENT_MISMATCH',
             'http_status': 401,
             'meaning': 'The bearer token was generated for a different environment.',
             'fix': 'Use sandbox tokens only on sandbox and production tokens only on production.'},
            {'code': 'LOGIKLU_ACCOUNT_INTELLIGENCE_NOT_FOUND',
             'http_status': 404,
             'meaning': 'No LogiKlu account intelligence record was found for the requested account_id.',
             'fix': 'Use a valid account_id available in the current LogiKlu Focus intelligence dataset.'},
            {'code': 'AUTH_API_CLIENT_INACTIVE',
             'http_status': 403,
             'meaning': 'The API client is inactive.',
             'fix': 'Activate the API client or use an active Bearer token.'},
            {'code': 'AUTH_SUBSCRIPTION_INACTIVE',
             'http_status': 403,
             'meaning': 'The client subscription is inactive.',
             'fix': 'Check the client subscription status.'},
            {'code': 'AUTH_IP_NOT_ALLOWED',
             'http_status': 403,
             'meaning': 'The request IP address is not allowed for this Bearer token.',
             'fix': 'Allow the requesting IP or use an approved network.'},
            {'code': 'VALIDATION_ERROR',
             'http_status': 422,
             'meaning': 'One or more request parameters are invalid.',
             'fix': 'Check parameter names, types, and allowed values.'},
            {'code': 'RESOURCE_NOT_FOUND',
             'http_status': 404,
             'meaning': 'The requested endpoint or resource was not found.',
             'fix': 'Check the endpoint path or resource ID.'},
            {'code': 'METHOD_NOT_ALLOWED',
             'http_status': 405,
             'meaning': 'The endpoint exists, but the HTTP method is not allowed.',
             'fix': 'Use the documented HTTP method for the endpoint.'},
            {'code': 'ACCOUNT_NOT_FOUND',
             'http_status': 404,
             'meaning': 'No account found for the given account ID.',
             'fix': 'Use a valid account ID.'},
            {'code': 'CONTACT_NOT_FOUND',
             'http_status': 404,
             'meaning': 'No contact found for the given contact ID.',
             'fix': 'Use a valid contact ID.'},
            {'code': 'INTERNAL_SERVER_ERROR',
             'http_status': 500,
             'meaning': 'Unexpected server-side error.',
             'fix': 'Retry later or contact LogiKlu technical support with request details.'}],
 'logging': {'title': 'API Request Logging',
             'description': 'LogiKlu stores API request logs internally for audit, troubleshooting, and support.',
             'logged_fields': ['oauth_client_id',
                               'auth_type',
                               'api_client_id',
                               'domain_id',
                               'client_database',
                               'environment',
                               'endpoint',
                               'request_method',
                               'ip_address',
                               'user_agent',
                               'request_params',
                               'request_body for POST, PUT, PATCH, DELETE',
                               'http_status_code',
                               'response_status',
                               'error_code',
                               'error_message',
                               'execution_time_ms',
                               'created_at'],
             'sandbox_table': 'lk_agent_api_request_logs_sandbox',
             'production_table': 'lk_agent_api_request_logs'},
 'auth_badge': 'JWT Bearer',
 'show_legacy_api_key': False,
 'quick_start_auth_type': 'bearer'}
